# Generated by Django 3.2.8 on 2021-10-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('award_title', models.CharField(max_length=100)),
                ('award_image_1', models.ImageField(upload_to='awards_1/')),
                ('award_image_2', models.ImageField(upload_to='awards_2/')),
                ('brief_profile', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
